apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/created-by: jmeter-operator
    app.kubernetes.io/instance: jmeter-operator
    app.kubernetes.io/managed-by: jmeter-operator
    app.kubernetes.io/name: jmeter-operator
    app.kubernetes.io/version: 5.4.1
    version: "0.1"
  name: jmeter-operator
  namespace: middleware-jmeter
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: jmeter-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: jmeter-operator
    spec:
      containers:
        - image: jmeter-operator:latest
          imagePullPolicy: IfNotPresent
          name: jmeter-operator
          resources:
            limits:
              cpu: "1"
              memory: 1G
            requests:
              cpu: "1"
              memory: 1G
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsUser: 2
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: jmeter-operator
      terminationGracePeriodSeconds: 30
