apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jmeter-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jmeter-operator
subjects:
  - kind: ServiceAccount
    name: jmeter-operator
    namespace: middleware-jmeter
